variables:
   WORKING_DIR: $CI_PROJECT_DIR/debian/output

build: 
  stage: build
  image: inakimalerba/autopkgtest-tin-chupala
  script:
    - mount -t tmpfs cgroup_root /sys/fs/cgroup
    - mkdir /sys/fs/cgroup/cpuset
    - mkdir /sys/fs/cgroup/devices
    - mount -t cgroup cpuset -o cpuset /sys/fs/cgroup/cpuset/
    - mount -t cgroup devices -o devices /sys/fs/cgroup/devices
    - cp lxc-net /etc/default/lxc-net
    - cp default.conf /etc/lxc/default.conf
    - |
        cat >/etc/lxc/lxc.conf <<EOT
        lxc.lxcpath=${WORKING_DIR}/lxc
        EOT
    - cat /etc/lxc/lxc.conf
    - /etc/init.d/lxc restart
    - /etc/init.d/libvirtd start
    - virsh net-start default
    - eatmydata debci setup
