variables:
   WORKING_DIR: $CI_PROJECT_DIR/lxc
   ARTIFACTS_DIR: $CI_PROJECT_DIR/artifacts

.config-legacy: &config-legacy
  before_script:
    - mkdir -p /etc/lxc
    - |
        cat >/etc/lxc/default.conf <<EOT
        lxc.network.type = veth
        lxc.network.link = lxcbr0
        lxc.network.flags = up
        lxc.network.hwaddr = 00:16:3e:xx:xx:xx
        lxc.aa_profile = unconfined
        EOT

.config-new: &config-new
  before_script:
    - mkdir -p /etc/lxc
    - |
        cat >/etc/lxc/default.conf <<EOT
        lxc.net.0.type = veth
        lxc.net.0.link = lxcbr0
        lxc.net.0.flags = up
        lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx
        lxc.apparmor.profile = unconfined
        EOT

.build-lxc: &build-lxc
  stage: build
  image: registry.salsa.debian.org/salsa-ci-team/images/base:${CI_JOB_NAME}
  script:
    - apt-get update
    - eatmydata apt-get install -y dnsmasq-base debci wget lxc libvirt-clients libvirt-daemon-system autopkgtest
    - | 
        cat >/etc/default/lxc-net <<EOT
        USE_LXC_BRIDGE="true"
        EOT
    - |
        cat >/etc/lxc/lxc.conf <<EOT
        lxc.lxcpath=${WORKING_DIR}/lxc
        EOT
    - /etc/init.d/lxc-net restart
    - mount -t tmpfs cgroup_root /sys/fs/cgroup
    - mkdir /sys/fs/cgroup/cpuset
    - mkdir /sys/fs/cgroup/devices
    - mount -t cgroup cpuset -o cpuset /sys/fs/cgroup/cpuset/
    - mount -t cgroup devices -o devices /sys/fs/cgroup/devices
    - /etc/init.d/lxc start
    - /etc/init.d/lxc restart
    - /etc/init.d/libvirtd start
    - virsh net-start default
    - debci setup
    - mkdir -p ${ARTIFACTS_DIR}
    - tar -cf ${ARTIFACTS_DIR}/lxc.tar -C ${WORKING_DIR} --exclude /dev .

  artifacts:
    paths:
    - ${ARTIFACTS_DIR}

.build-legacy:
    extends: .build-lxc
    <<: *config-legacy

.build-new:
    extends: .build-lxc
    <<: *config-new

unstable:
    extends: .build-new

# Enable buster when base image is generated. TODO
#buster:
#    extends: .build-new

stretch-backports:
    extends: .build-legacy

stretch:
    extends: .build-legacy

jessie:
    extends: .build-legacy
