variables:
   WORKING_DIR: $CI_PROJECT_DIR/lxc
   ARTIFACTS_DIR: $CI_PROJECT_DIR/artifacts
   debci_quiet: 'false'

.build-lxc: &build-lxc
  stage: build
  image: registry.salsa.debian.org/salsa-ci-team/images/autopkgtest
  script:
    - NAME="${NAME:-$CI_JOB_NAME}"
    - |
        cat >/etc/lxc/default.conf <<EOT
        lxc.net.0.type = veth
        lxc.net.0.link = lxcbr0
        lxc.net.0.flags = up
        lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx
        lxc.apparmor.profile = unconfined
        EOT
    - | 
        cat >/etc/default/lxc-net <<EOT
        USE_LXC_BRIDGE="true"
        EOT
    - |
        cat >/etc/lxc/lxc.conf <<EOT
        lxc.lxcpath=${WORKING_DIR}
        EOT
    - /etc/init.d/lxc-net restart || true
    - mount -t tmpfs cgroup_root /sys/fs/cgroup
    - mkdir /sys/fs/cgroup/cpuset
    - mkdir /sys/fs/cgroup/devices
    - mount -t cgroup cpuset -o cpuset /sys/fs/cgroup/cpuset/
    - mount -t cgroup devices -o devices /sys/fs/cgroup/devices
    - /etc/init.d/lxc start
    - /etc/init.d/lxc restart
    - /etc/init.d/libvirtd start
    - virsh net-start default
    - debci setup --suite ${NAME}

  after_script:
    - mkdir -p ${ARTIFACTS_DIR}
    - tar -cf ${ARTIFACTS_DIR}/lxc.tar --exclude /dev -C ${WORKING_DIR} .

  artifacts:
    paths:
    - ${ARTIFACTS_DIR}

.not-a-real-distribution-after-script: &not-a-real-distribution-after-script
    after_script:
        - mv ${WORKING_DIR}/autopkgtest-${NAME}-amd64 ${WORKING_DIR}/autopkgtest-${CI_JOB_NAME}-amd64
        - echo "deb http://deb.debian.org/debian ${CI_JOB_NAME} main" > ${WORKING_DIR}/autopkgtest-${CI_JOB_NAME}-amd64/rootfs/etc/apt/sources.list.d/sci.list
        - sed -i "s/${NAME}/${CI_JOB_NAME}/g" ${WORKING_DIR}/autopkgtest-${CI_JOB_NAME}-amd64/config
        - mkdir -p ${ARTIFACTS_DIR}
        - tar -cf ${ARTIFACTS_DIR}/lxc.tar --exclude /dev -C ${WORKING_DIR} .

experimental:
    variables:
        NAME: 'unstable'
    extends: .build-lxc
    <<: *not-a-real-distribution-after-script

unstable:
    extends: .build-lxc

testing:
    extends: .build-lxc

stable:
    extends: .build-lxc

bullseye:
    extends: .build-lxc

buster:
    extends: .build-lxc

stretch:
    extends: .build-lxc

# Jessie mirrors are not working
#jessie:
#    extends: .build-lxc

stretch-backports:
    variables:
        NAME: 'stretch'
    extends: .build-lxc
    <<: *not-a-real-distribution-after-script
